spring.application.name=interview
server.port=8080

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_db
spring.datasource.username=interview_user
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver


# Dev tools
spring.jpa.open-in-view=true
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


# Logging
spring.output.ansi.enabled=ALWAYS
logging.level.web=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.apache.catalina=WARN
logging.level.org.apache.coyote=WARN
logging.level.org.apache.tomcat=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.org.flywaydb.core=WARN
logging.level.com.example.interview=DEBUG